### ISSUE TITLE
返回的答案会有重复的情况

### ISSUE THREAD

**Issue by socialok** [deepdialog/t_ad_help_data#2]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/90542573/156113050-55b99775-3f56-45de-9b32-f5edcf9a2b5f.png">
<img width="636" alt="image" src="https://user-images.githubusercontent.com/90542573/156113116-f59b272b-8574-4717-890e-43c9c6f00415.png">

**Comment by tianrking** [comment]
已修复
